openapi: "3.0.0"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://localhost:8080
paths:
  /api/auth/extend-token:
    post:
      summary: "Extend the token"
      description: "API này dùng để tạo mới accessToken để duy trì đăng nhập trên client"
      tags:
        - AUTH
      security:
        - bearerAuth: []
      parameters:
        - name: refreshToken
          in: cookie
          description: refreshToken
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Tạo mới accessToken thành công"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Tạo mới accessToken thành công"
                      accessToken:
                        type: string
                        example: "<access_token>"
                  statusCode:
                    type: number
                    example: 200
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Unauthorized"
                  statusCode:
                    type: number
                    example: 401
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "404":
          description: "Không tìm thấy tài nguyên"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Không tìm thấy tài nguyên"
                  statusCode:
                    type: number
                    example: 404
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
