openapi: "3.0.0"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://localhost:8080
paths:
  /api/auth/change-password:
    post:
      summary: "Change password"
      description: "API này dùng để đổi mật khẩu tài khoản thông qua mã xác thực"
      tags:
        - AUTH
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                code:
                  type: string
                newPass:
                  type: string
      responses:
        "200":
          description: "Đổi mật khẩu thành công"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Đổi mật khẩu thành công"
                  statusCode:
                    type: number
                    example: 200
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "400":
          description: "Mã code không chính xác"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Mã code không chính xác"
                  statusCode:
                    type: number
                    example: 400
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "401":
          description: "Code hết hạn"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Code hết hạn"
                  statusCode:
                    type: number
                    example: 401
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "404":
          description: "Dữ liệu không tồn tại"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Dữ liệu không tồn tại"
                  statusCode:
                    type: number
                    example: 404
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "409":
          description: "Mật khẩu mới trùng với mật khẩu đã sử dụng gần đây"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Mật khẩu mới trùng với mật khẩu đã sử dụng gần đây"
                  statusCode:
                    type: number
                    example: 409
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
