openapi: "3.0.0"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://localhost:8080
paths:
  /api/auth/send-code-verify-email:
    post:
      summary: "Send code verify email"
      description: "API này dùng để gửi mail mã xác nhận email cho người dùng"
      tags:
        - AUTH
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        "200":
          description: "Gửi mã xác thực email thành công"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Gửi mã xác thực email thành công"
                  statusCode:
                    type: number
                    example: 200
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "404":
          description: "Email không tồn tại"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Email không tồn tại"
                  statusCode:
                    type: number
                    example: 404
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
