openapi: "3.0.0"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://localhost:8080
paths:
  /api/auth/login:
    post:
      summary: "Đăng nhập"
      description: "API này dùng để người dùng đăng nhập"
      tags:
        - AUTH
      requestBody:
        description: Thông tin đăng nhập
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "string"
                password:
                  type: string
                  example: "string"
      responses:
        "200":
          description: "Đăng nhập thành công"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Đăng nhập thành công"
                      accessToken:
                        type: string
                        example: "<access_token>"
                  statusCode:
                    type: number
                    example: 200
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "401":
          description: "Mật khẩu không chính xác"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Mật khẩu không chính xác"
                  statusCode:
                    type: number
                    example: 401
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "404":
          description: "Email đã tồn tại"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Email đã tồn tại"
                  statusCode:
                    type: number
                    example: 404
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
