openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://localhost:8080
paths:
  /api/users/profile:
    get:
      summary: "Lấy thông tin người dùng đang đăng nhập"
      description: "API này trả về thông tin của người dùng đang đăng nhập thông qua accessToken"
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - name: token
          in: header
          description: accessToken
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "lấy danh sách người dùng thành công"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            user_id:
                              type: integer
                              example: 1
                            username:
                              type: string
                              example: John Doe
                            email:
                              type: string
                              example: johndoe@example.com
                            phone_number:
                              type: string
                              example: 0987654321
                            address:
                              type: string
                              example: 123 Main St, City, State, Zip Code
                            role:
                              type: string
                              example: "user"
                            avatar_url:
                              type: string
                              example: "https://example.com/avatar.jpg"
                            is_email_verified:
                              type: boolean
                              example: true
                      statusCode:
                        type: number
                        example: 200
                      dateTime:
                        type: string
                        format: date-time
                        example: "2022-01-01T12:00:00Z"
        "400":
          description: "Lấy thông tin người dùng không thành công"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Lấy thông tin người dùng không thành công"
                  statusCode:
                    type: number
                    example: 400
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Unauthorized"
                  statusCode:
                    type: number
                    example: 401
                  dateTime:
                    type: string
                    format: date-time
                    example: "2022-01-01T12:00:00Z"
